
title: "Mohd. Sultan Ahammad"
description: "Assistant Professor, CSE @ MBSTU | Research: Digital Security, ML, DL, Cybersecurity, Software Engineering"
url: "https://sultanahammad.github.io"
baseurl: ""

# Use Minimal Mistakes via remote theme (GitHub Pages compatible)
remote_theme: "mmistakes/minimal-mistakes"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author and social links (replace placeholders)


# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      classes: wide
      author_profile: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Theme tweaks
search: true
minimal_mistakes_skin: "default"  # try "air", "dark", "contrast" etc.
